# Generated by Django 4.1.1 on 2023-03-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_special_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='special_requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
